description: Setup Gradle
name: Setup Gradle

runs:
    using: composite
    steps:
        -   name: Setup Gradle
            uses: gradle/gradle-build-action@v2
            with:
                gradle-version: wrapper
